/* eslint-disable */
export const STR = {
  ar: {
    tagline: 'المهارة المناسبة والفريق المناسب.',
    support: 'أخبرنا ما الذي تبنيه والمهارات التي ينقصك، ونعرض لك من يمتلكها فعلًا من المطوّرين والمصمّمين المستعدين للتعاون.',
    chipMatch: 'مطابقة بالمهارات', chipChat: 'محادثة بعد القبول', chipBilingual: 'عربي / إنجليزي',
    authEyebrow: 'تسجيل الدخول', welcomeTitle: 'أهلًا بعودتك', welcomeSubtitle: 'سجّل الدخول لتكمل بناء فريقك.',
    email: 'البريد الإلكتروني', password: 'كلمة المرور', passwordHint: '٨ أحرف على الأقل', togglePassword: 'إظهار/إخفاء كلمة المرور', working: 'جارٍ…', emailPh: 'example@example.com', passwordPh: 'اكتب كلمة المرور',
    login: 'تسجيل الدخول', rememberMe: 'تذكّرني على هذا الجهاز', signup: 'إنشاء حساب', logout: 'تسجيل الخروج',
    getStarted: 'ابدأ الآن', signedInAs: 'مسجّل الدخول باسم',
    backHome: 'العودة إلى الصفحة الرئيسية', next: 'التالي', back: 'السابق', remove: 'حذف',
    secAccount: 'بيانات الحساب', aboutYou: 'عنك', aboutYouHint: 'هذه البيانات تظهر للآخرين في بطاقتك وملفك.', fullName: 'الاسم الكامل',
    namePh: 'اسمك الكامل', rolePh: 'مثال: مطوّر خلفية',
    bioPh: 'جملة أو جملتان عمّا تبنيه وما تستمتع بالعمل عليه.',
    expPh: 'سنوات الخبرة، التدريب، المسابقات، المصادر المفتوحة…',
    stepAccountTitle: 'أنشئ حسابك', stepAccountSub: 'دقيقتان للإعداد، ثم ابدأ بإيجاد الأشخاص المناسبين.',
    stepSkillsTitle: 'ما المهارات التي تتقنها؟', stepSkillsSub: 'أضف مهاراتك وحدّد مستواك في كل واحدة — هذا ما يُطابَق عند البحث.',
    stepProjectsTitle: 'أعمالك السابقة', stepProjectsSub: 'أضف مشاريع سابقة لتعطي فكرة أوضح عمّا أنجزته. يمكنك تخطي هذه الخطوة.',
    searchOrAddPh: 'اكتب أول حروف المهارة… أو اكتب مهارة جديدة لإضافتها',
    addSkill: 'إضافة',
    skillExamplesHint: 'أمثلة — اكتب أول حروف أي مهارة للبحث في القائمة كاملة.',
    skillNoMatch: 'ما فيه مهارة بهذا الاسم — اضغط «إضافة» لإضافتها كمهارة جديدة.',
    skillMoreHint: 'اكتب للبحث في بقية المهارات.',
    searchResults: 'نتائج البحث',
    /* notifTitle / notifEyebrow / notifSubtitle معرّفة أصلًا في نصوص التصميم أدناه */
    notifEmptyTitle: 'ما فيه إشعارات بعد',
    notifEmptyDesc: 'حين يصلك طلب تعاون، أو يُقبل طلب أرسلته، أو تتحرك إحدى مجموعاتك — يظهر هنا.',
    notifMarkRead: 'تعليم الكل كمقروء', notifClear: 'مسح الكل',
    notifUnreadOne: 'إشعار جديد', notifUnreadMany: 'إشعارات جديدة',
    pickFirstTitle: 'ابدأ باختيار مهارة',
    pickFirstDesc: 'اختر من الأعلى المهارات التي تحتاجها في شريكك، وسنعرض هنا من يمتلكها مرتّبين حسب نسبة التطابق. كل مهارة تضيفها تجعل الترتيب أدق.',
    browseAll: 'أو تصفّح كل الأعضاء',
    selectedAndLevels: 'المهارات المختارة ومستوياتها', noSkillsYet: 'لم تُضف أي مهارة بعد — اختر من القائمة أعلاه.',
    projectsHint: 'اختياري — يمكنك إضافتها لاحقًا من «ملفي».',
    addProject: 'إضافة مشروع', projectTitle: 'العنوان', projectRole: 'دورك',
    projectDescription: 'الوصف', projectTech: 'التقنيات',
    projectTitlePh: 'مثال: منصة حجوزات', projectRolePh: 'مثال: مطوّرة واجهات', projectDescPh: 'وصف مختصر لما بنيته وأثره.',
    guestEnter: 'الدخول بدون تسجيل', demoAccount: 'حساب تجريبي', noAccount: 'جديد في تيم أب؟',
    guestBadge: 'وضع الضيف', gateTitle: 'أنشئ حسابك لتكمل', gateBody: 'التصفّح مفتوح للجميع، أما فتح الملفات والمحادثات وإرسال طلبات التعاون فتحتاج حسابًا — يستغرق دقيقتين.', gateSearchTitle: 'انتهت عمليات البحث المجانية', gateSearchBody: 'جرّبت ٣ عمليات بحث كضيف. أنشئ حسابًا لبحث بلا حدود، وللتواصل مع من يناسبك.', gateLater: 'لاحقًا', guestBanner: 'أنت تتصفح كضيف — التصفّح فقط.', createAccount: 'إنشاء حساب',
    langToggle: 'EN', cancel: 'إلغاء', save: 'حفظ التغييرات', savedMsg: 'تم حفظ الملف الشخصي.',
    needName: 'اكتب اسمك الكامل.', needRole: 'اكتب تخصصك التقني — هو أول ما يشوفه الآخرون.', needSkills: 'أضف مهارة واحدة على الأقل — بدونها ما تظهر في نتائج البحث.', optionalStep: 'اختياري — تقدر تضيفها لاحقًا من «ملفي».', requiredMark: 'مطلوب', stepAccount: 'الحساب', stepProfile: 'الملف الشخصي', stepDiscover: 'الاستكشاف',
    onbEyebrow: 'إعداد الملف الشخصي', onbTitle: 'أخبرنا بما تقدّمه للفريق',
    onbSubtitle: 'مهاراتك هي ما يبحث عنه الآخرون. كلما كانت أدق، كانت نتائج المطابقة أفضل.',
    finishSetup: 'إنهاء الإعداد',
    photo: 'الصورة الشخصية', changePhoto: 'رفع صورة', removePhoto: 'إزالة', photoHint: 'PNG أو JPG، حتى ٣ ميجابايت. تظهر للجميع في الاستكشاف والمحادثات.', fName: 'الاسم', fRole: 'التخصص التقني', fBio: 'نبذة مختصرة', fOpenTo: 'منفتح على',
    fOpenToHint: 'هذا يحدد عمليات البحث التي تظهر فيها.',
    mySkills: 'مهاراتي', mySkillsHint: 'هذه هي المهارات التي سيطابقها الآخرون عند البحث.',
    myProjectsHint: 'أضيفي أو احذفي مشاريعك في أي وقت — تظهر للجميع في ملفك.',
    squadTitle: 'فِرقي', squadEyebrow: 'مجموعات العمل', squadSubtitle: 'المجموعات التي تعمل معها الآن. كل مجموعة لها دردشة خاصة بأعضائها.',
    newGroup: 'مجموعة جديدة', inviteTitle: 'دعوات المجموعات', inviteHint: 'شوف من في الفريق وما الذي يبنونه قبل ما تنضم.', joinGroup: 'انضمام', createGroup: 'إنشاء المجموعة', groupChat: 'فتح دردشة المجموعة',
    groupActions: 'خيارات المجموعة', manageGroup: 'إدارة المجموعة', deleteGroup: 'حذف المجموعة', leaveGroup: 'مغادرة المجموعة', groupInfo: 'معلومات المجموعة', ownerBadge: 'أنت المالك', memberBadge: 'عضو', allowMembers: 'السماح للأعضاء بالإدارة', allowMembersHint: 'إذا فُعّلت، يقدر الأعضاء يعدّلون الاسم والوصف ويضيفون ويحذفون أعضاء. حذف المجموعة يبقى لك وحدك.', saveGroup: 'حفظ التعديلات', editGroup: 'تعديل المجموعة',
    groupName: 'اسم المجموعة', groupNamePh: 'مثال: فريق هاكاثون جدة',
    groupDesc: 'وصف المجموعة', groupDescPh: 'ما الذي تبنيه المجموعة، وكيف تنسّقون؟',
    groupMembers: 'الأعضاء', squadEmptyTitle: 'لا توجد مجموعات بعد',
    squadEmptyDesc: 'أنشئ مجموعة وأضف زملاءك إليها لتتابعوا العمل في مكان واحد.',
    navTeam: 'زملائي', teamEyebrow: 'زملاء التعاون', directMessage: 'رسالة مباشرة',
    teamEmptyTitle: 'لا يوجد زملاء بعد',
    teamEmptyDesc: 'يظهر هنا كل شخص قبِلتم التعاون معه. ابدأ بإرسال طلب من الاستكشاف، أو اقبل طلبًا وصلك.',
    navHome: 'الرئيسية', menu: 'القائمة', navDiscover: 'استكشاف', navRequests: 'الطلبات', navMessages: 'الرسائل', navNotif: 'الإشعارات', navProfile: 'ملفي',
    discoverEyebrow: 'استكشاف', discoverTitle: 'اعثر على شريكك',
    searchPlaceholder: 'ابحث باسم أو تخصص أو مهارة…',
    all: 'الكل', hackathons: 'الهاكاثونات', projects: 'المشاريع', lookingFor: 'أبحث عن',
    tabHackathon: 'شريك هاكاثون', tabProject: 'عضو مشروع',
    filterBySkills: 'اختر المهارات التي تحتاجها', clearSkills: 'حذف الكل',
    findMyTeam: 'ابحث', viewProfile: 'عرض الملف', sendShort: 'إرسال الطلب',
    emptyMatchTitle: 'لا يوجد عضو مطابق',
    emptyMatchDesc: 'جرّب مهارات أقل أو أعم، أو أعد نوع التعاون إلى «الكل».',
    resultsEyebrow: 'نتائج المطابقة', changeSkills: 'تغيير المهارات', requiredSkills: 'المهارات المطلوبة:',
    exact: 'مطابقات كاملة', partial: 'أقرب المطابقات الجزئية',
    emptyResultsTitle: 'لا أحد يطابق هذه المهارات بعد',
    emptyResultsDesc: 'جرّب اختيار مهارات أقل أو أعم — مثل مهارة عامة كـ Backend أو Frontend.',
    backToDiscover: 'العودة إلى الاستكشاف',
    skillsLevels: 'المهارات والمستويات', projectsTitle: 'المشاريع السابقة', experience: 'الخبرة ذات الصلة',
    interests: 'اهتمامات التعاون', memberSince: 'عضو منذ ٢٠٢٤',
    sendRequest: 'إرسال طلب تعاون', openChat: 'فتح المحادثة', pendingCta: 'الطلب قيد الانتظار',
    reqModalEyebrow: 'طلب تعاون', reqType: 'نوع التعاون', reqMessage: 'رسالة (اختياري)',
    requestsEyebrow: 'الطلبات والإشعارات', requestsTitle: 'طلبات التعاون',
    requestsSubtitle: 'قبول الطلب يفتح تلقائيًا محادثة خاصة مع ذلك الشخص.',
    received: 'الواردة', sent: 'المُرسلة', accept: 'قبول', reject: 'رفض',
    statusPending: 'قيد الانتظار', statusAccepted: 'مقبول', statusRejected: 'مرفوض',
    receivedAt: 'وردت', sentAt: 'أُرسلت',
    emptyReqTitle: 'لا توجد طلبات بعد', emptyReqDesc: 'عندما يرغب أحدهم في التعاون معك، سيظهر طلبه هنا.',
    goDiscover: 'اذهب إلى الاستكشاف',
    messagesEyebrow: 'الرسائل', messagesTitle: 'المحادثات',
    messagesSubtitle: 'تُفتح المحادثات الخاصة تلقائيًا بعد قبول طلب التعاون.',
    live: 'مباشر', today: 'اليوم', send: 'إرسال',
    allConversations: 'كل المحادثات', closeChat: 'إغلاق المحادثة',
    pickConvTitle: 'اختر محادثة',
    pickConvDesc: 'اختر زميلًا من القائمة على الجانب لتفتح محادثتكما وتكمل من حيث توقفتم.',
    emptyChatTitle: 'لا توجد محادثات بعد',
    emptyChatDesc: 'تُفتح المحادثة بعد قبول طلب التعاون — أرسل طلبًا من ملف شخصي، أو اقبل طلبًا وصلك.',
    checkRequests: 'مراجعة الطلبات',
    notifEyebrow: 'النشاط', notifTitle: 'الإشعارات', notifSubtitle: 'كل ما جرى حول تعاوناتك.',
    meEyebrow: 'ملفي', meTitle: 'تعديل ملفك الشخصي',
    meSubtitle: 'حافظ على تحديث مهاراتك — فهي تحدد عمليات البحث التي تظهر فيها.',
    settingsEyebrow: 'الحساب والتفضيلات',
    settingsSubtitle: 'تحكّم بما يصلك من تنبيهات، وبإعدادات حسابك.',
    notifCard: 'الإشعارات', notifCardHint: 'اختر ما تريد أن يصلك فقط.',
    notifInterest: 'طلبات الاهتمام', notifInterestHint: 'حين يرسل إليك أحدهم طلب تعاون.',
    notifAccepted: 'الطلبات المقبولة', notifAcceptedHint: 'حين يُقبل طلب أرسلته وتُفتح المحادثة.',
    notifGroups: 'تحديثات المجموعات', notifGroupsHint: 'الرسائل والتغييرات في فِرقك.',
    accountCard: 'الحساب',
    languageHint: 'لغة الواجهة واتجاه الصفحة.',
    changePassword: 'تغيير كلمة المرور', changePasswordHint: 'نرسل رابطًا آمنًا إلى بريدك.',
    logoutHint: 'الخروج من هذا الجهاز فقط.',
    logoutConfirm: 'هل تريد تسجيل الخروج؟', logoutConfirmDesc: 'ستحتاج إلى تسجيل الدخول مجددًا للوصول إلى ملفك ومحادثاتك.',
    yes: 'نعم، خروج', no: 'لا',
    deleteAccount: 'حذف الحساب', deleteAccountHint: 'يُحذف ملفك وطلباتك ومحادثاتك نهائيًا.',
    viewAsOthers: 'اعرضه كما يراه الآخرون', editMine: 'تعديل ملفي', settings: 'الإعدادات', language: 'اللغة',
    levelBeginner: 'مبتدئ', levelIntermediate: 'متوسط', levelAdvanced: 'متقدم',
    openBoth: 'هاكاثونات ومشاريع', openHackathon: 'الهاكاثونات فقط', openProject: 'المشاريع فقط',
    toastSent: 'أُرسل الطلب.', toastAccepted: 'قُبل الطلب — فُتحت المحادثة.', toastRejected: 'رُفض الطلب.', toastSaved: 'تم الحفظ.',
  },
  en: {
    tagline: 'Find the right skills. Build the right team.',
    support: 'Tell us what you are building and which skills you are missing, and we will show you the developers and designers who actually have them.',
    chipMatch: 'Skill-based matching', chipChat: 'Chat after acceptance', chipBilingual: 'Arabic / English',
    authEyebrow: 'Log in', welcomeTitle: 'Welcome back', welcomeSubtitle: 'Log in to keep building your team.',
    email: 'Email', password: 'Password', passwordHint: 'At least 8 characters', togglePassword: 'Show/hide password', working: 'Working…', emailPh: 'example@example.com', passwordPh: 'Enter your password',
    login: 'Log in', rememberMe: 'Remember me on this device', signup: 'Sign up', logout: 'Log out',
    getStarted: 'Get Started', signedInAs: 'Signed in as',
    backHome: 'Back to home', next: 'Next', back: 'Back', remove: 'Remove',
    secAccount: 'Account details', aboutYou: 'About you', aboutYouHint: 'This is what others see on your card and profile.', fullName: 'Full name',
    namePh: 'Your full name', rolePh: 'e.g. Backend Developer',
    bioPh: 'One or two sentences about what you build and what you enjoy working on.',
    expPh: 'Years of experience, internships, competitions, open-source work…',
    stepAccountTitle: 'Create your account', stepAccountSub: 'Two minutes to set up. Then start finding the right people.',
    stepSkillsTitle: 'Which skills do you have?', stepSkillsSub: 'Add your skills and set your level in each — this is what searches match against.',
    stepProjectsTitle: 'Your previous work', stepProjectsSub: 'Add past projects to show what you have shipped. You can skip this step.',
    searchOrAddPh: 'Type the first letters of a skill… or type a new one to add it',
    addSkill: 'Add',
    skillExamplesHint: 'Examples — type the first letters of any skill to search the full list.',
    skillNoMatch: 'No skill matches that — press “Add” to create it as a new skill.',
    skillMoreHint: 'Type to search the rest of the skills.',
    searchResults: 'Search results',
    /* notifTitle / notifEyebrow / notifSubtitle already defined in the design strings below */
    notifEmptyTitle: 'No notifications yet',
    notifEmptyDesc: 'When someone sends you a request, accepts one of yours, or your squads move — it shows up here.',
    notifMarkRead: 'Mark all as read', notifClear: 'Clear all',
    notifUnreadOne: 'new notification', notifUnreadMany: 'new notifications',
    pickFirstTitle: 'Start by picking a skill',
    pickFirstDesc: 'Choose the skills you need from above and the people who have them will appear here, ranked by match. Every skill you add sharpens the ranking.',
    browseAll: 'Or browse everyone',
    selectedAndLevels: 'Selected skills & levels', noSkillsYet: 'No skills added yet — pick from the list above.',
    projectsHint: 'Optional — you can add them later from My Profile.',
    addProject: 'Add a project', projectTitle: 'Title', projectRole: 'Your role',
    projectDescription: 'Description', projectTech: 'Technologies',
    projectTitlePh: 'e.g. Booking platform', projectRolePh: 'e.g. Frontend Developer', projectDescPh: 'A short description of what you built and its impact.',
    guestEnter: 'Enter without signing up', demoAccount: 'Demo account', noAccount: 'New to TeamUp?',
    guestBadge: 'Guest mode', gateTitle: 'Create your account to continue', gateBody: 'Browsing is open to everyone, but opening profiles, chatting and sending requests need an account — it takes two minutes.', gateSearchTitle: 'Free searches used up', gateSearchBody: 'You have used your 3 guest searches. Create an account for unlimited search and to reach out to people.', gateLater: 'Later', guestBanner: 'You are browsing as a guest — viewing only.', createAccount: 'Create an account',
    langToggle: 'ع', cancel: 'Cancel', save: 'Save changes', savedMsg: 'Profile saved.',
    needName: 'Enter your full name.', needRole: 'Enter your technical role — it is the first thing people see.', needSkills: 'Add at least one skill — without it you will not appear in search results.', optionalStep: 'Optional — you can add these later from My Profile.', requiredMark: 'required', stepAccount: 'Account', stepProfile: 'Profile', stepDiscover: 'Discover',
    onbEyebrow: 'Profile setup', onbTitle: 'Tell us what you bring to a team',
    onbSubtitle: 'Your skills are what other builders search for. The more accurate they are, the better your matches.',
    finishSetup: 'Finish setup',
    photo: 'Profile photo', changePhoto: 'Upload photo', removePhoto: 'Remove', photoHint: 'PNG or JPG, up to 3 MB. Shown to everyone in Discover and chats.', fName: 'Name', fRole: 'Technical role', fBio: 'Short bio', fOpenTo: 'Open to',
    fOpenToHint: 'This controls which searches you appear in.',
    mySkills: 'My Skills', mySkillsHint: 'These are the skills other people will match against when they search.',
    myProjectsHint: 'Add or remove your projects any time — they show on your public profile.',
    squadTitle: 'My Squads', squadEyebrow: 'My squads', squadSubtitle: 'The groups you are working with right now. Each one has its own private chat.',
    newGroup: 'New group', inviteTitle: 'Group invitations', inviteHint: 'See who is on the team and what they are building before you join.', joinGroup: 'Join', createGroup: 'Create group', groupChat: 'Open group chat',
    groupActions: 'Group actions', manageGroup: 'Manage group', deleteGroup: 'Delete group', leaveGroup: 'Leave group', groupInfo: 'Group info', ownerBadge: 'You own this', memberBadge: 'Member', allowMembers: 'Let members manage', allowMembersHint: 'When on, members can edit the name and description and add or remove members. Deleting the group stays yours alone.', saveGroup: 'Save changes', editGroup: 'Edit group',
    groupName: 'Group name', groupNamePh: 'e.g. Jeddah Hackathon Squad',
    groupDesc: 'Group description', groupDescPh: 'What is the group building, and how do you coordinate?',
    groupMembers: 'Members', squadEmptyTitle: 'No groups yet',
    squadEmptyDesc: 'Create a group and add your teammates so the work lives in one place.',
    navTeam: 'Teammates', teamEyebrow: 'Accepted collaborations', directMessage: 'Direct message',
    teamEmptyTitle: 'No teammates yet',
    teamEmptyDesc: 'Everyone you have agreed to collaborate with shows up here. Send a request from Discover, or accept one you received.',
    navHome: 'Home', menu: 'Menu', navDiscover: 'Discover', navRequests: 'Interests', navMessages: 'Messages', navNotif: 'Notifications', navProfile: 'My Profile',
    discoverEyebrow: 'Discover', discoverTitle: 'Find your partner',
    searchPlaceholder: 'Search by name, role or skill…',
    all: 'All', hackathons: 'Hackathons', projects: 'Projects', lookingFor: "I'm looking for",
    tabHackathon: 'Hackathon partner', tabProject: 'Project member',
    filterBySkills: 'Pick the skills you need', clearSkills: 'Clear all',
    findMyTeam: 'Search', viewProfile: 'View Profile', sendShort: 'Send request',
    emptyMatchTitle: 'No member matches',
    emptyMatchDesc: 'Try fewer or broader skills, or set the collaboration type back to All.',
    resultsEyebrow: 'Match results', changeSkills: 'Change skills', requiredSkills: 'Required skills:',
    exact: 'Exact matches', partial: 'Closest partial matches',
    emptyResultsTitle: 'Nobody matches those skills yet',
    emptyResultsDesc: 'Try selecting fewer or broader skills — for example a general skill like Backend or Frontend.',
    backToDiscover: 'Back to Discover',
    skillsLevels: 'Skills & levels', projectsTitle: 'Previous projects', experience: 'Relevant experience',
    interests: 'Collaboration interests', memberSince: 'Member since 2024',
    sendRequest: 'Send Collaboration Request', openChat: 'Open chat', pendingCta: 'Request pending',
    reqModalEyebrow: 'Collaboration request', reqType: 'Collaboration type', reqMessage: 'Message (optional)',
    requestsEyebrow: 'Interests & notifications', requestsTitle: 'Interests',
    requestsSubtitle: 'Accepting a request automatically opens a private chat with that person.',
    received: 'Received', sent: 'Sent', accept: 'Accept', reject: 'Reject',
    statusPending: 'Pending', statusAccepted: 'Accepted', statusRejected: 'Rejected',
    receivedAt: 'Received', sentAt: 'Sent',
    emptyReqTitle: 'No requests yet', emptyReqDesc: 'When someone wants to team up with you, their request will appear here.',
    goDiscover: 'Go to Discover',
    messagesEyebrow: 'Messages', messagesTitle: 'Conversations',
    messagesSubtitle: 'Private chats open automatically once a collaboration request is accepted.',
    live: 'Live', today: 'Today', send: 'Send',
    allConversations: 'All conversations', closeChat: 'Close chat',
    pickConvTitle: 'Pick a conversation',
    pickConvDesc: 'Choose a teammate from the list to open your chat and pick up where you left off.',
    emptyChatTitle: 'No conversations yet',
    emptyChatDesc: 'Chat unlocks after a collaboration request is accepted — send one from a profile, or accept a request you received.',
    checkRequests: 'Check requests',
    notifEyebrow: 'Activity', notifTitle: 'Notifications', notifSubtitle: 'Everything that happened around your collaborations.',
    meEyebrow: 'My profile', meTitle: 'Edit your profile',
    meSubtitle: 'Keep your skills current — they decide which searches you show up in.',
    settingsEyebrow: 'Account & preferences',
    settingsSubtitle: 'Control what reaches you, and manage your account.',
    notifCard: 'Notifications', notifCardHint: 'Keep only what you want to hear about.',
    notifInterest: 'Interest requests', notifInterestHint: 'When someone sends you a collaboration request.',
    notifAccepted: 'Accepted requests', notifAcceptedHint: 'When a request you sent is accepted and the chat opens.',
    notifGroups: 'Group updates', notifGroupsHint: 'Messages and changes in your squads.',
    accountCard: 'Account',
    languageHint: 'Interface language and page direction.',
    changePassword: 'Change password', changePasswordHint: 'We email you a secure link.',
    logoutHint: 'Sign out on this device only.',
    logoutConfirm: 'Log out?', logoutConfirmDesc: 'You will need to log in again to reach your profile and chats.',
    yes: 'Yes, log out', no: 'No',
    deleteAccount: 'Delete account', deleteAccountHint: 'Your profile, requests and chats are permanently removed.',
    viewAsOthers: 'View as others see it', editMine: 'Edit my profile', settings: 'Settings', language: 'Language',
    levelBeginner: 'Beginner', levelIntermediate: 'Intermediate', levelAdvanced: 'Advanced',
    openBoth: 'Hackathons & Projects', openHackathon: 'Hackathons only', openProject: 'Projects only',
    toastSent: 'Request sent.', toastAccepted: 'Request accepted — chat opened.', toastRejected: 'Request rejected.', toastSaved: 'Saved.',
  },
};

export const CATEGORIES = [
  { key: 'AI & Agents', ar: 'الذكاء الاصطناعي والوكلاء', skills: [
    'Artificial Intelligence', 'AI Agents', 'Multi-Agent Systems', 'LLMs', 'Prompt Engineering',
    'RAG', 'LangChain', 'LlamaIndex', 'OpenAI API', 'Claude API', 'Hugging Face', 'Fine-tuning',
    'Vector Databases', 'Embeddings', 'MCP', 'Generative AI', 'NLP', 'Speech Recognition',
    'Chatbots', 'AI Ethics'] },
  { key: 'Machine Learning', ar: 'تعلّم الآلة', skills: [
    'Machine Learning', 'Deep Learning', 'PyTorch', 'TensorFlow', 'Keras', 'scikit-learn',
    'Computer Vision', 'Reinforcement Learning', 'MLOps', 'Model Deployment', 'Neural Networks'] },
  { key: 'Data', ar: 'البيانات والتحليل', skills: [
    'Data Analysis', 'Data Engineering', 'Data Visualization', 'Pandas', 'NumPy', 'Spark',
    'ETL', 'Power BI', 'Tableau', 'Statistics', 'R', 'Excel', 'Big Data', 'Airflow'] },
  { key: 'Networks & Security', ar: 'الشبكات والأمن السيبراني', skills: [
    'Networking', 'Computer Networks', 'TCP/IP', 'DNS', 'HTTP', 'Cybersecurity',
    'Network Security', 'Penetration Testing', 'Ethical Hacking', 'Cryptography', 'Firewalls',
    'VPN', 'Wireshark', 'Nmap', 'OWASP', 'Incident Response', 'CCNA'] },
  { key: 'Backend', ar: 'الواجهات الخلفية', skills: [
    'Backend', 'Node.js', 'Python', 'FastAPI', 'Django', 'Flask', 'Go', 'Java', 'Spring Boot',
    'C#', '.NET', 'PHP', 'Laravel', 'Ruby on Rails', 'Rust', 'C++', 'Express.js', 'NestJS',
    'REST API', 'GraphQL', 'gRPC', 'Microservices', 'WebSockets'] },
  { key: 'Frontend', ar: 'الواجهات الأمامية', skills: [
    'Frontend', 'HTML', 'CSS', 'JavaScript', 'TypeScript', 'React', 'Next.js', 'Vue', 'Angular',
    'Svelte', 'Tailwind CSS', 'Bootstrap', 'SASS', 'Redux', 'Vite', 'Three.js', 'WebGL',
    'Accessibility', 'Responsive Design'] },
  { key: 'Mobile', ar: 'تطبيقات الجوال', skills: [
    'Flutter', 'Dart', 'React Native', 'Swift', 'SwiftUI', 'Kotlin', 'Android', 'iOS'] },
  { key: 'Database', ar: 'قواعد البيانات', skills: [
    'SQL', 'NoSQL', 'PostgreSQL', 'MySQL', 'SQLite', 'MongoDB', 'Redis', 'Firebase', 'Supabase',
    'Elasticsearch', 'Prisma', 'Oracle', 'Neo4j', 'Database Design'] },
  { key: 'DevOps & Cloud', ar: 'العمليات والسحابة', skills: [
    'Docker', 'Kubernetes', 'AWS', 'Azure', 'Google Cloud', 'CI/CD', 'GitHub Actions', 'Jenkins',
    'Terraform', 'Ansible', 'Linux', 'Bash', 'Nginx', 'Git', 'Monitoring', 'Kafka', 'Serverless'] },
  { key: 'Design & Product', ar: 'التصميم والمنتج', skills: [
    'UI/UX', 'Figma', 'Prototyping', 'User Research', 'Design Systems', 'Wireframing',
    'Adobe XD', 'Photoshop', 'Illustrator', 'After Effects', 'Motion Design', 'Branding',
    'Product Management', 'Agile', 'Scrum', 'User Testing'] },
  { key: 'Game & 3D', ar: 'الألعاب والتصميم ثلاثي الأبعاد', skills: [
    'Unity', 'Unreal Engine', 'Game Design', 'Blender', '3D Modeling', 'AR/VR', 'Animation'] },
  { key: 'Emerging Tech', ar: 'تقنيات ناشئة', skills: [
    'Blockchain', 'Smart Contracts', 'Solidity', 'Web3', 'IoT', 'Embedded Systems', 'Arduino',
    'Raspberry Pi', 'Robotics', 'Quantum Computing', 'Digital Twins'] },
  { key: 'Other', ar: 'مهارات عامة', skills: [
    'Technical Writing', 'Team Leadership', 'Presentation', 'Research', 'Problem Solving'] },
];

/** أمثلة تظهر أول ما تفتح الصفحة — الباقي يظهر بالكتابة في البحث. */
export const SKILL_EXAMPLES = [
  'Artificial Intelligence', 'AI Agents', 'Machine Learning', 'Networking', 'Cybersecurity',
  'React', 'Python', 'Node.js', 'Flutter', 'UI/UX', 'PostgreSQL', 'Docker',
];

